FROM openjdk:11
ADD target/netflix-zuul-api-gateway-0.0.1-SNAPSHOT.jar netflix-zuul-api-gateway-0.0.1-SNAPSHOT.jar
EXPOSE 8761
ENTRYPOINT ["java", "-jar", "netflix-zuul-api-gateway-0.0.1-SNAPSHOT.jar"]  