FROM openjdk:11
ADD target/currency-conversion-service-0.0.1-SNAPSHOT.jar currency-conversion-service-0.0.1-SNAPSHOT.jar
EXPOSE 8100
ENTRYPOINT ["java", "-jar", "currency-conversion-service-0.0.1-SNAPSHOT.jar"]  