FROM openjdk:11
ADD target/currency-exchange-service-0.0.1-SNAPSHOT.jar currency-exchange-service-0.0.1-SNAPSHOT.jar
EXPOSE 8000
ENTRYPOINT ["java", "-jar", "currency-exchange-service-0.0.1-SNAPSHOT.jar"]  